name: Update Confluence

on:
  push:
    branches:
      - '**'

jobs:
  update-confluence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
     
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
       
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: |
        if git diff --name-only | grep -q 'ERROR_CODE.md'; then
          python update_confluence.py
        else
          echo "error.md has not been modified."
        fi

